package export

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// GenerateCurl returns a shell script with one curl command per endpoint.
func GenerateCurl(s StoreReader, opts ExportOptions) ([]byte, error) {
	if opts.ConfidenceThreshold == 0 {
		opts.ConfidenceThreshold = 0.9
	}
	if opts.InfoTitle == "" {
		opts.InfoTitle = "Discovered API"
	}

	endpoints, err := s.GetEndpoints()
	if err != nil {
		return nil, fmt.Errorf("curl: get endpoints: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString("#!/bin/sh\n")
	buf.WriteString("# Generated by probe\n")
	buf.WriteString("# Usage: BASE_URL=https://api.example.com sh api.sh\n\n")
	buf.WriteString(`BASE_URL="${BASE_URL:-http://localhost:4000}"`)
	buf.WriteString("\n")

	for _, ep := range endpoints {
		if ep.Protocol == "grpc" {
			continue
		}
		if ep.CallCount < opts.MinCalls {
			continue
		}

		method := strings.ToUpper(ep.Method)

		fmt.Fprintf(&buf, "\n# ---------------------------------------------------------------------------\n")
		fmt.Fprintf(&buf, "# %s %s\n", method, ep.PathPattern)
		fmt.Fprintf(&buf, "# ---------------------------------------------------------------------------\n")

		// Warn about path params that need to be set.
		pathParams := pathParamRe.FindAllStringSubmatch(ep.PathPattern, -1)
		for _, m := range pathParams {
			fmt.Fprintf(&buf, "# set %s before running\n", m[1])
		}

		// Build the URL substituting {id} → $id.
		urlPath := pathParamRe.ReplaceAllStringFunc(ep.PathPattern, func(match string) string {
			name := match[1 : len(match)-1]
			return "$" + name
		})

		fieldRows, err := s.GetFieldConfidence(ep.ID)
		if err != nil {
			return nil, fmt.Errorf("curl: get field confidence for endpoint %d: %w", ep.ID, err)
		}

		reqSchema := buildSchemaFromConfidence(fieldRows, "request", opts.ConfidenceThreshold)
		hasBody := reqSchema != nil && (method == "POST" || method == "PUT" || method == "PATCH")

		if hasBody {
			template := schemaToJSONTemplate(reqSchema)
			raw, _ := json.MarshalIndent(template, "  ", "  ")
			fmt.Fprintf(&buf, "curl -s -X %s \"$BASE_URL%s\" \\\n", method, urlPath)
			fmt.Fprintf(&buf, "  -H \"Content-Type: application/json\" \\\n")
			fmt.Fprintf(&buf, "  -H \"Accept: application/json\" \\\n")
			fmt.Fprintf(&buf, "  -d '%s'\n", string(raw))
		} else {
			fmt.Fprintf(&buf, "curl -s -X %s \"$BASE_URL%s\" \\\n", method, urlPath)
			fmt.Fprintf(&buf, "  -H \"Accept: application/json\"\n")
		}
	}

	return buf.Bytes(), nil
}
