package export

import (
	"bytes"
	"strings"
	"testing"
)

const sampleCurlScript = `#!/bin/sh
# Generated by probe
BASE_URL="${BASE_URL:-http://localhost:4000}"

# ---------------------------------------------------------------------------
# GET /api/users
# ---------------------------------------------------------------------------
curl -s -X GET "$BASE_URL/api/users" \
  -H "Accept: application/json"

# ---------------------------------------------------------------------------
# POST /api/users
# ---------------------------------------------------------------------------
curl -s -X POST "$BASE_URL/api/users" \
  -H "Content-Type: application/json" \
  -d '{"name":""}'
`

const additionalCurlBlock = `
# ---------------------------------------------------------------------------
# DELETE /api/users/{id}
# ---------------------------------------------------------------------------
# set id before running
curl -s -X DELETE "$BASE_URL/api/users/$id" \
  -H "Accept: application/json"
`

// TestParseScriptEndpointKeys verifies extraction of "METHOD /path" keys.
func TestParseScriptEndpointKeys(t *testing.T) {
	t.Parallel()
	keys := ParseScriptEndpointKeys([]byte(sampleCurlScript))
	if !keys["GET /api/users"] {
		t.Error("expected GET /api/users in keys")
	}
	if !keys["POST /api/users"] {
		t.Error("expected POST /api/users in keys")
	}
	if len(keys) != 2 {
		t.Errorf("expected 2 keys; got %d", len(keys))
	}
}

// TestMergeScript_AllNew verifies all incoming blocks are appended when existing
// script has none of them.
func TestMergeScript_AllNew(t *testing.T) {
	t.Parallel()
	existing := []byte("#!/bin/sh\nBASE_URL=\"${BASE_URL:-http://localhost:4000}\"\n")
	incoming := []byte(sampleCurlScript)

	merged, added := MergeScript(existing, incoming)
	if len(added) != 2 {
		t.Errorf("expected 2 added; got %d: %v", len(added), added)
	}
	if !bytes.Contains(merged, []byte("GET /api/users")) {
		t.Error("expected GET /api/users in merged output")
	}
	if !bytes.Contains(merged, []byte("POST /api/users")) {
		t.Error("expected POST /api/users in merged output")
	}
}

// TestMergeScript_SomeExist verifies that existing blocks are preserved and
// only new blocks from incoming are appended.
func TestMergeScript_SomeExist(t *testing.T) {
	t.Parallel()
	existing := []byte(sampleCurlScript)
	incoming := []byte(sampleCurlScript + additionalCurlBlock)

	merged, added := MergeScript(existing, incoming)
	if len(added) != 1 {
		t.Errorf("expected 1 added; got %d: %v", len(added), added)
	}
	if !strings.Contains(added[0], "DELETE") {
		t.Errorf("expected DELETE in added key; got %q", added[0])
	}
	if !bytes.Contains(merged, []byte("DELETE /api/users/{id}")) {
		t.Error("expected DELETE block in merged output")
	}
	// Existing blocks must appear exactly once.
	count := strings.Count(string(merged), "GET /api/users")
	if count != 1 {
		t.Errorf("expected GET /api/users exactly once; got %d", count)
	}
}

// TestMergeScript_NoDuplicates verifies merging identical scripts produces no
// additions and no duplicated blocks.
func TestMergeScript_NoDuplicates(t *testing.T) {
	t.Parallel()
	script := []byte(sampleCurlScript)
	merged, added := MergeScript(script, script)
	if len(added) != 0 {
		t.Errorf("expected 0 added; got %d: %v", len(added), added)
	}
	count := strings.Count(string(merged), "GET /api/users")
	if count != 1 {
		t.Errorf("expected GET /api/users exactly once; got %d", count)
	}
}
